### ISSUE TITLE
Lua error

### ISSUE THREAD

**Issue by keflatbn** [Oppzippy/GoldStockSummary#25]
Hi, 
I get the below Lua error:

2x GoldStockSummary/Modules/Tracker.lua:144: Unable to determine guild owner: 136 members
[string "=[C]"]: in function `error'
[string "@GoldStockSummary/Modules/Tracker.lua"]:144: in function `GetGuildOwner'
[string "@GoldStockSummary/Modules/Tracker.lua"]:113: in function `UpdateOwner'
[string "@GoldStockSummary/Modules/Tracker.lua"]:99: in function `UpdateGuildAndOwner'
[string "@GoldStockSummary/Modules/Tracker.lua"]:50: in function <GoldStockSummary/Modules/Tracker.lua:45>

Locals:
(*temporary) = "Unable to determine guild owner: 136 members"****

**Comment by Oppzippy** [comment]
Thanks for reporting, I'll look into this in a couple days.

**Comment by Oppzippy** [comment]
I'm trying to reproduce the issue but no luck so far.

1. Is this on retail or classic?
2. Does this always occur when logging in or only sometimes?
3. If you `/reload` after you're already logged in, does the error occur again, or is it only the initial login?
4. Is the number of guild members reported in the error message (Unable to determine guild owner: **136** members) correct?

**Comment by keflatbn** [comment]
Hi, sorry for the late reply!
1. its on latest retail
2. It happens sometimes, but I seem to have identified that it occurs on characters that are not on a connected realm as the guild master and also not the same faction. Not sure it that makes it easier to identify
3. If I reload, the error is not appearing again, only on initial login
4. yes the reported number of members is correct, both horde and alliance characters and as mentioned in point2, across connected and non-connected realms.

That said, I havent seen the error since 11.0.2 of retail so maybe it solved itself on blizz side?

**Comment by Oppzippy** [comment]
a7e2da1d970d5f7a5141bcd7359234e0695be26f should fix it, so the corresponding alpha version and newer will have the fix. I'll do a release soon.
