### ISSUE TITLE
[Feature Request] Show total amount of gold combined from all realms

### ISSUE THREAD

**Issue by zeenk** [Oppzippy/GoldStockSummary#3]
Would it be possible we could get a total amount of gold somewhere so it's easier to tell how much gold we have on the account from all realms combined? maybe another tab just to show total amount on the account or if you could fit it into the realms tab somewhere? :)

**Comment by Oppzippy** [comment]
Thanks for the suggestion. I added a total money tab in 34923aa3d07f60f74b4f55ab5880f4bdadeb0adf.

**Comment by zeenk** [comment]
Perfect, thanks! :)

One more thing I noticed with the addon, pressing esc does not work to close the menu, not sure if that is intended or not?

**Comment by Oppzippy** [comment]
Esc not closing the menu was just something I hadn't considered. Fixed in 03ac44df856ecb44b5b4a3bb8428de8fb6f80f58.
