### ISSUE TITLE
Lua error

### ISSUE THREAD

**Issue by zeenk** [Oppzippy/GoldStockSummary#4]
Got this lua error when I logged in, there was also a bunch of guild members logging in in chat so maybe that had something to do with it, a quick relog seem to have fixed it tho, didn't get it second time I logged in, but here is the lua I got:

Message: ...nterface\AddOns\GoldStockSummary\Modules\Tracker.lua:132: bad argument #2 to 'format' (string expected, got nil)
Time: Sun Sep 11 21:01:43 2022
Count: 1
Stack: ...nterface\AddOns\GoldStockSummary\Modules\Tracker.lua:132: bad argument #2 to 'format' (string expected, got nil)
[string "=[C]"]: ?
[string "=[C]"]: in function `format'
[string "@Interface\AddOns\GoldStockSummary\Modules\Tracker.lua"]:132: in function `GetGuildNameAndRealm'
[string "@Interface\AddOns\GoldStockSummary\Modules\Tracker.lua"]:65: in function `UpdateGuildAndOwner'
[string "@Interface\AddOns\GoldStockSummary\Modules\Tracker.lua"]:32: in function <...nterface\AddOns\GoldStockSummary\Modules\Tracker.lua:27>

Locals:

**Comment by Oppzippy** [comment]
Thanks, fixed in 64b3a6cdd0dfb9fffcaea98540334a061bf40bc8.
